### ISSUE TITLE
superclass is missing in generated lexer/parser classes

### ISSUE THREAD

**Issue by maiermic** [mazzutti/antlr4dart#2]
Generated lexer/parser classes contain a syntax error: superclass is missing

Got:
class SomeLanguageLexer extends { ... }
class SomeLanguageParser extends { ... }

Expected:
class SomeLanguageLexer extends Lexer { ... }
class SomeLanguageParser extends Parser { ... }

**Comment by mazzutti** [comment]
Hi,

it should be fixed now!
Thanks to report!!

**Comment by maiermic** [comment]
Thank you very much. May I ask you, if you know how to visualize a parser, that has been created with antlr4dart? I can not use TestRig (alias grun), because my grammar contains dart actions.

**Comment by mazzutti** [comment]
Hi Michael,

unfortunately TestRing wasn't ported until now. Patches are welcome!

I don't know what exactly TestRing do, but you can compile your gramar with the -listener flag and then
watch the enter and exit of the parser rule calls with your own listener instance. Maybe it can help you!

**Comment by maiermic** [comment]
I had a look at TestRig. You pass the name of a grammar and it uses reflection to create lexer and parser objects of that grammar. If option is gui, it opens a TreeViewer (part of the runtime), that displays the Tree object (returned by the rule call on the parser object).

To use reflection/mirroring in dart (TestRig port), we need to import generated lexer and parser files.  At the moment, it is not possible to [import a file at runtime](http://code.google.com/p/dart/issues/detail?id=10530). There are some workarounds you can use (e.g. manipulating imports of a file and run it as a new process on the VM), but you still have to draw the tree. That's the actual aim.

Thus, I wrote a function _treeToDot_, that creates a graph description in [DOT Language](http://www.graphviz.org/doc/info/lang.html), which can be rendered with [Graphviz](http://www.graphviz.org/) ([Guide](http://www.graphviz.org/pdf/dotguide.pdf)). You can use it similar to Trees.toStringTree. Maybe you like to add it to the runtime.

``` dart
import 'package:antlr4dart/antlr4dart.dart';

/**
 * Returns a graph description in
 * [DOT Language](http://www.graphviz.org/doc/info/lang.html)
 * of the parse tree.
 *
 * You can use
 * [Graphviz](http://www.graphviz.org)
 * to render a graph.
 */
String treeToDot(Tree tree, dynamic rules, [String graphName = "G"]) {
  if (rules is Parser) rules = rules.ruleNames;
  var sb = new StringBuffer(); // all statements are written to this buffer
  Function treeToDotNode = (Tree t) => new DotNode(Trees.getNodeText(t, rules));
  // depth first traversal
  List<int> breadthIndices = [0]; // begin at first child in tree
  List<DotNode> path = [treeToDotNode(tree)]; // path of visited nodes
  int d = 0; // depth level
  int p = 0; // start printing the path from this level
  Tree t = tree; // current tree
  int i; // current breadth index
  while(d >= 0) {
    i = breadthIndices[d];
    if(i < t.childCount) {
      // visit next child
      breadthIndices[d]++;
      d++;
      breadthIndices.add(0);
      t = t.getChild(i);
      path.add(treeToDotNode(t));
    } else {
      // action that has to be done on every node
      if(i == 0) {
        // node is a leaf => add edges
        sb.writeln('  ${_edgeStatement(path.sublist(p))}');
      }
      sb.writeln('  ${path[d].nodeStatement}');
      // go back to parent
      d--;
      t = t.parent;
      p = d;
      path.removeLast();
      breadthIndices.removeLast();
    }
  } // finished traversal
  return '''
digraph $graphName {
$sb
}
''';
}

/**
 * Returns a edge statement, that links all passed [nodes].
 */
String _edgeStatement(List<DotNode> nodes) {
  return "${nodes.join(" -> ")};";
}

/**
 * Simple representation of a node of the
 * [DOT Language](http://www.graphviz.org/doc/info/lang.html).
 */
class DotNode {
  static int _n = 0;
  static String _generateID() {
    return "n${_n++}";
  }

  String _id;
  String _label;

  DotNode(label) {
    _id = _generateID();
    // escape all special whitespace characters
    label = label.replaceAll("\t", r"\\t").replaceAll("\n", r"\\n").replaceAll("\r", r"\\r");
    _label = '"$label"';
  }

  String get id => _id;
  String get label => _label;
  String get nodeStatement => "$id [label=$label];";

  /**
   * Returns only the identifier of the node.
   * This makes it easier for functions,
   * that work with a list of nodes
   * (e.g. [_edgeStatement]).
   */
  String toString() {
    return id;
  }
}
```
