### ISSUE TITLE
make _tokenFacSourcePair public

### ISSUE THREAD

**Issue by maiermic** [mazzutti/antlr4dart#3]
Hi,
I would like to call `tokenFactory` and pass `_tokenFacSourcePair` to create and inject tokens in my grammar, but I can not access `_tokenFacSourcePair` in my generated lexer, because it is a private member of super class `Lexer`. In Java version `_tokenFacSourcePair` is protected and can be accessed. Please make `_tokenFacSourcePair` public or provide a getter.

Thanks,
Michael

**Comment by mazzutti** [comment]
Hi Michael,

maybe you could create and use your own `tokenFactory` by extending `CommonTokenFactory` and replace de default `call` implementation. Then you could inject tokens when your `tokenFactory` is called.

let me know if this solves your problem.
Tiago

**Comment by maiermic** [comment]
I already use a different approach and override `emitToken` and `nextToken`. I call `tokenFactory` and pass `_tokenFacSourcePair` as well as `type`, `text`, etc. to create a new token and pass it to `emitToken` to inject it.
I can not access `_tokenFacSourcePair`, but I just realized that I can create a new `Pair` in my lexer:

``` dart
Pair<TokenProvider, StringSource> get _tokenFacSourcePair =>
    new Pair<TokenProvider, StringSource>(this, inputSource);
```
