### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by thosakwe** [mazzutti/antlr4dart#4]
Hi! I'm interested in sending in a few PR's to upgrade this library to work with the latest versions of Dart.

**Comment by mazzutti** [comment]
Hello, please go ahead! I think I can find some free time to do the merge and send it to pub.dartlang.org. Otherwise if you agree I can add you as a uploader.

Please also modify the AUTHORS file to add your data.

**Comment by thosakwe** [comment]
Thanks for the response! We can actually get Dart landed in the official ANTLR4 repo. There's an issue open for Dart support. If you sign their CLA, then I can go ahead and get this going.

**Comment by thosakwe** [comment]
https://github.com/antlr/antlr4/issues/1367

**Comment by mazzutti** [comment]
OK! I have signed their CLA [antlr/antlr4/pull/1989](https://github.com/antlr/antlr4/pull/1989/commits/715bfccb8033106663adb73ce319bf9a6bef868e).

**Comment by thosakwe** [comment]
Thank you very much!
